import type { Metadata } from "next";
import { GeistMono } from "geist/font/mono";
import { Agentation } from "agentation";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistMono.variable} h-full antialiased dark`}
      style={{ fontFamily: `${GeistMono.style.fontFamily}, monospace` }}
      suppressHydrationWarning
    >
          {/* {process.env.NODE_ENV === "development" && <Agentation />} */}

      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
